server:
  servlet:
    context-path: /
    port: 8080
spring:
  mail:
    host: smtp.gmail.com
    username: trung03trung@gmail.com
    password: yhzztttnihpqlclt
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring
    username: itsol
    password: 123456

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 144694474399-4je2amacsr47q8vkei1nmo54cmgdiidb.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000
twilio:
  account_sid: ACf52dea0eeae683f5f2c3c6fb681e67dd
  auth_token: 7ba059acf801bc946894e67761c7b330
  trial_number: +12232185034